# UNet mini, loss mixte CE + Dice, augmentation activ√©e. Dimensions 512x1024.
run_name = "unet_small_ce_dice_extra"
model_type = "unet_small"
input_height = 512
input_width  = 1024
batch_size = 2
epochs = 30
learning_rate = 0.0002
loss_type = "ce_dice"
class_weights = [1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0]
augment = true
mixed_precision = true
early_stopping_patience = 10
top_k_checkpoints = 3
